### ISSUE TITLE
Can't seem to install latest beta

### ISSUE THREAD

**Issue by Skrell** [JackMerlin/USBAccelerator#4]
___________________________________________________________________
Where do you want to download me?
  1  =  from GitHub
  2  =  from GitLab
___________________________________________________________________
Please enter
1
Set it up!
Please wait while the download is starting...
Download failed. Please check network connection and router time.
[: bad number
WARNING: Missing files, please reinstall
___________________________________________________________________
Welcome, here is the control panel of USB Accelerator v2.0-beta2

  1  =  Enable
  2  =  Disable

  3  =  Download and Update
  4  =  Other Settings
  5  =  Read Documents

  8  =  Re-install
  9  =  Uninstall

  e  =  Exit
___________________________________________________________________
Please enter

**Comment by Skrell** [comment]
If i try to reinstall I get this:

Are you sure you want to Re-install?
NOTE: Re-install should only be used to try to solve issue.
If you want to update, should use the update function.

  y  =  Yes
  n  =  No
___________________________________________________________________
Please Enter
y
___________________________________________________________________
Do you want to keep configuration?

  1  =  Keep
  2  =  Don't keep
  0  =  Return to Control Panel
___________________________________________________________________
Please Enter
2
Please wait for a while, if successful will reload...
USB Accelerator: Reinstall failed, no internet connection
USB Accelerator: Please report this code to the developer for help resolve the issue:
USB Accelerator: ERROR:RT-AC1900-384.16-2.0-beta2-1-100-10
Re-install failed
Please wait while the download is starting...
Download failed. Please check network connection and router time.
[: bad number
WARNING: Missing files, please reinstall

**Comment by JackMerlin** [comment]
Hi, @Skrell 
The check network connection function will first use the ntp_ready variable to check. In other words, you need to make sure that your router time is correct. because the download uses HTTPS to connect to GitHub or GitLab. it needs the correct time to verify the server certificate.
The ntp_ready variable may report "1" only after synchronizing with the NTP server to get the correct time. 

You can check the ntp_ready variable using the command below, if it returns null or "0", and your router time is correct, please tell me, because it will be interesting for me.
```
nvram get ntp_ready
```

You can also try to change this variable manually if you think your router time is correct. This will trick the USB Accelerator's network connection check.
```
nvram set ntp_ready="1"
nvram commit
```
After entering the above command and then installing, it should help you alleviate this problem.

Glad to see any reply, and I will continue to pay attention to this issue :)

**Comment by Skrell** [comment]
Ok you are correct my router time is incorrect.... how the hell do I fix that?  (how did that even happen??)

**Comment by JackMerlin** [comment]
> Ok you are correct my router time is incorrect.... how the hell do I fix that? (how did that even happen??)

You can try to login to your router, and then go to `Administration`-`System`, modify to the available `NTP Server`, when you modify it, click `NTP Link` to synchronize the time immediately, and you can check the time in the `system logs` page.


I don't know how it happened, usually this error will not happen.

**Comment by Skrell** [comment]
I think I figured it out and managed to get the script to install.  I think this issue can be closed for now.  I'm not noticing much of a speed improvement but I don't think that's your fault and really just 1 of several issues I'm currently having with this router...  Might be time to upgrade to the ac86u.   Thank you for your time and effort!

**Comment by JackMerlin** [comment]
I also have 1900P. On my router, it has increased from 50MB/s to about 70MB/s. Maybe you can share more information to help me judge why it didn't work.

For 86U, it may not work because the transmission speed can reach 1Gbps even without USB Accelerator. So there is no more room for improvement there. but, there may be improvements under wireless, I am not sure.

**Comment by Skrell** [comment]
Wow that's great news!  So in general I'm wondering if something failed on my router hardware wise.  
To summarize:
I updated to the latest Merlin because my gf was having issues with her laptop saying there was "no internet connection" intermittently when connected to my Wifi.  I had her plug into the ethernet jack and it still did it.  I NEVER experienced this issue and tend to believe it is related to her company's laptop and possibly a Win10 issue.  However, I simultaneously have been having issues transferring large files from 1 usb3.0 harddrive to another usb3.0 harddrive when BOTH are attached to my ac68u.  Smaller files will transfer (and their speed typically hovers around r/w speeds of 15MB/s  but larger ones will take a VERY long time and then the file will be corrupt on the receiving end after it finishes.  I've tried different harddrives, using the usb 2.0 port, turning off everything in the router that could interfere with CPU utilization (QOS, logging, bandwidth monitor, etc...) nothing seems to help.     Here are my settings: https://ibb.co/V3RHLdZ

**Comment by JackMerlin** [comment]
> I updated to the latest Merlin because my gf was having issues with her laptop saying there was "no internet connection" intermittently when connected to my Wifi. I had her plug into the ethernet jack and it still did it. I NEVER experienced this issue and tend to believe it is related to her company's laptop and possibly a Win10 issue.

Have you tried to reset your router after the update? and you should set up your router manually, do not import the previous config file. I recommend always using the latest firmware, whether it is merlin or stock, because they contain many errors and security fixes. and the merlin firmware used a similar method to improve the usb transfer speed from 384.9 begin, just like I did. then did you try to update your NIC driver? I think Windows 10 updates sometimes mess up everything and they will give you the wrong driver. you should try to download the latest driver from your device manufacturer website.

> However, I simultaneously have been having issues transferring large files from 1 usb3.0 harddrive to another usb3.0 harddrive when BOTH are attached to my ac68u. Smaller files will transfer (and their speed typically hovers around r/w speeds of 15MB/s but larger ones will take a VERY long time and then the file will be corrupt on the receiving end after it finishes. I've tried different harddrives, using the usb 2.0 port, turning off everything in the router that could interfere with CPU utilization (QOS, logging, bandwidth monitor, etc...) nothing seems to help. Here are my settings:

RT-AC68U (RT-AC1900P) has only one USB 3.0 port and the other is USB 2.0. when you copy a file from first usb drive to second usb drive, it will actually have poor performance, not only because of usb 2.0, what's more, it needs to download the file of the first usb drive to your computer first, and then upload it to the second drive. 
When you copy a drive file to your computer, it will consume a lot of memory and cpu of the router. This is because the cpu performance of the router is very poor. It is not a NAS. and when you are uploading the file to another drive at the same time, the cpu of the router may be too tired at this time, thus causing file corrupt.
One possible method is to copy the file inside the router system without going through any network. but this may not be possible because the router does not have a file manager, router is not NAS!! unless you do that in SSH.
The easiest and most reliable way is to connect one usb drive to your computer and copy the files from the router's drive to your computer.
Finally, I do not recommend that you enable guest login, which is not safe for your network, and also don't use the administrator account, you can create a new account for your usb share.

**Comment by Skrell** [comment]
What tool do you typically use to benchmark the usb speeds?  I did a full factory reset + reinstalled your script and the speeds are the same.  I'm using CrystalDiskMark7 to benchmark read/write speeds.

**Comment by JackMerlin** [comment]
> What tool do you typically use to benchmark the usb speeds? I did a full factory reset + reinstalled your script and the speeds are the same. I'm using CrystalDiskMark7 to benchmark read/write speeds.

Don't use CrystalDiskMark because it will only tell you the maximum speed of the transfer, not the real speed. You can use the Windows copy function to test, it will display a progress bar, so you can know the speed of each time.

> and the merlin firmware used a similar method to improve the usb transfer speed from 384.9 begin

But as I said before, It may not work well on the new Merlin firmware, because the Merlin firmware has also changed `socket options`. Even if I change more options, that's not the key, the key option is `socket options`.

**Comment by JackMerlin** [comment]
BTW, the Merlin firmware has just been updated and includes new OpenSSL security fixes. I don't think you need to reset again, if you have done it before.
It is recommended to update because this security hole is dangerous.
https://www.snbforums.com/threads/release-asuswrt-merlin-384-17-and-384-13_8-are-now-available.63636/

**Comment by Skrell** [comment]
So I was wrong, even after the factory reset, I still can't transfer large files from 1 usb HD to another across a USB HUB I have attached to my router.  This USED to work no problem (many months ago) but no matter what I do I can't figure out what's changed.(unless something in the hardware itself is broken)   Does this screenshot tell you anything?  Perhaps the RAM is too low?  I still have CPU left when it's frozen...  So I'm at a loss... https://ibb.co/rfWY7tJ
What do you think about hooking up this device to my router via ethernet and accessing my external HDs through it?  https://www.amazon.com/Anker-Gigabit-Ethernet-Converter-Support/dp/B014ZOJX7W

**Comment by Skrell** [comment]
> 
> 
> BTW, the Merlin firmware has just been updated and includes new OpenSSL security fixes. I don't think you need to reset again, if you have done it before.
> It is recommended to update because this security hole is dangerous.
> https://www.snbforums.com/threads/release-asuswrt-merlin-384-17-and-384-13_8-are-now-available.63636/

thank you for the tip!

**Comment by JackMerlin** [comment]
> So I was wrong, even after the factory reset, I still can't transfer large files from 1 usb HD to another across a USB HUB I have attached to my router. This USED to work no problem (many months ago) but no matter what I do I can't figure out what's changed.(unless something in the hardware itself is broken) Does this screenshot tell you anything? Perhaps the RAM is too low? I still have CPU left when it's frozen... So I'm at a loss.

This is not normal, you are right, you still have CPU and RAM. so, I think you should test and transfer files from one of your drives to your computer, not from one drive to another one. if you can get the normal speed, I think your router is not faulty.

For me, when I transfer a file from the router to my computer, it will provide about 70MB/s speed over Gigabit Ethernet. the CPU core 1 is close to 100%, and CPU core 2 is close to 80%. The RAM usage rate exceeds 90%.

> What do you think about hooking up this device to my router via ethernet and accessing my external HDs through it?

Do not use the USB 3.0 Hub, because the router does not support USB 3.0 Hub, even if it can work, it can only work in USB 2.0 mode. and, the router's Ethernet interface does not support any CONVERSION TO USB!!! Don't waste your money.

> thank you for the tip!

You're welcome
