### ISSUE TITLE
Problem with USBAccelerator install, Asus RT-AC56U running Asuswrt-merlin 384.6

### ISSUE THREAD

**Issue by gurkagurk** [JackMerlin/USBAccelerator#5]
Hey there.

Thanks for the rad firmware. I would really love to get the usb accelerator installed but I'm running into issues when attempting to run the commands listed for installation. 

After running the command:

> /usr/sbin/wget --tries=3 --timeout=3 --no-check-c
ertificate -O "/tmp/usbaccelerator.sh" "https://raw.githubusercontent.com/JackMe
rlin/USBAccelerator/master/usbaccelerator.sh" && chmod 755 /tmp/usbaccelerator.s
h && sh /tmp/usbaccelerator.sh --github --shellui

It comes back with:

> /tmp/usbaccelerator.sh: line 3520: can't create /jffs/addons/usbaccelerator/CONFIG: nonexistent directory
/tmp/usbaccelerator.sh: line 3520: can't create /jffs/addons/usbaccelerator/CONFIG: nonexistent directory
sed: /jffs/addons/usbaccelerator/CONFIG: No such file or directory
chmod: /jffs/addons/usbaccelerator/CONFIG: No such file or directory
Set it up!
Please wait while the download is starting...
cp: can't create '/jffs/addons/usbaccelerator/usbaccelerator.sh': No such file or directory
mv: can't rename '/tmp/usbstatus.png': No such file or directory
WARNING: Missing files, please reinstall

When I try to Enable USBAccelerator, it comes back with this error:

USB Accelerator: ERROR:RT-AC56U-384.6-2.0-1-4

Im also getting denied when I try to create any directories within /jffs, it states that it is a "read only filesystem". Does this have anything to do with the issue?

Thanks for any help :)

-Gurkagurk

**Comment by JackMerlin** [comment]
Hello @gurkagurk 
This error seems to be caused by JFFS read-only.
You can enter the code below to check your JFFS status in SSH client:
```shell
nvram get jffs2_on
nvram get jffs2_enable
```
They should both return `1`.  If it are not `1`, it means that your [JFFS Partition](https://github.com/RMerl/asuswrt-merlin.ng/wiki/JFFS) is not available. USB Accelerator needs to save the script to your JFFS, so that it can be run every time the router is started or when usb drive is mounted.

You can try to enable jffs using the code below, if the return is not `1`. **Please [backup](https://github.com/RMerl/asuswrt-merlin.ng/wiki/JFFS#backing-up-the-jffs-partition) any important data in your JFFS before using the code below**, as this will format the JFFS partition.
```shell
nvram set jffs2_on=1
nvram set jffs2_enable=1
nvram set jffs2_format=1
nvram commit
reboot
```
I think this will probably work, hope to hear from you.


If the JFFS status returns both are `1`, then please enter the code below and tell me the return content:
```shell
df -h
ls -l -a /jffs
```
Jack

**Comment by gurkagurk** [comment]
Hey there @JackMerlin 

Thanks for the quick reply!

Both of these commands come back with the value of 1.

>  nvram get jffs2_on
> nvram get jffs2_enable

I then tried to enable the jffs using the commands:

> nvram set jffs2_on=1
> nvram set jffs2_enable=1
> nvram set jffs2_format=1
> nvram commit
> reboot

And then I tried to install again, but am met with the same issue.

Output of **df -h** and **ls -l -a /jffs** below:

> Filesystem                Size      Used Available Use% Mounted on
> /dev/root                31.4M     31.4M         0 100% /
> devtmpfs                124.8M         0    124.8M   0% /dev
> tmpfs                   124.9M    764.0K    124.1M   1% /tmp
> /dev/sdb2               931.2G    350.8G    580.3G  38% /tmp/mnt/sdb2
> /dev/sda2               465.3G    304.6G    160.7G  65% /tmp/mnt/sda2
> /dev/sda3               465.7G    111.3G    354.5G  24% /tmp/mnt/sda3
> admin@mandalls:/tmp/home/root# ls -l -a /jffs
> drwxr-xr-x    2 admin    root             3 Jul 25  2018 .
> drwxr-xr-x   17 admin    root           320 Jul 25  2018 ..



I am on root user aren't I ? Still getting a read-only filesystem issue...


-Gurkagurk

**Comment by JackMerlin** [comment]
Hello, @gurkagurk 
Thanks for your output, this seems to be a firmware issue, that your router is not mounted the jffs partition, which is very strange, because all merlin firmware and 380 and higher stock firmware are support the jffs partition.

The possible cause of this issue is that you have updated from a very old firmware to a newer firmware, and did not restore the factory settings after the update. You can try to solve this problem using the command below:
```shell
nvram unset jffs2_size
nvram commit
reboot
```
After your router reboot, If you use the `df -h` command again and see the `/jffs`, the problem has been solved.
The normal output should look like this:
```
Filesystem	Size	Used	Available	Use%	Mounted	on
/dev/root	31.4M	31.4M	0	100%	/
devtmpfs	124.8M	0	124.8M	0%	/dev
tmpfs		124.9M	764.0K	124.1M	1%	/tmp
/dev/mtdblock4	62.8M	1.7M	61.1M	3%	/jffs
```
I hope this will help you. If it is not useful, you may need to feedback this issue in [the SNB forum](https://www.snbforums.com/forums/asuswrt-merlin.42/), because it is a firmware issue and beyond my control.


> I am on root user aren't I ?

If you use SSH to login to your router, you are the root user, but the flash chip of the router is read-only. Only specific firmware allows you to write data to the flash chip, such as merlin firmware and stock 380+ firmware.


***References***
https://www.snbforums.com/threads/jffs2.16187/#post-111370
https://www.snbforums.com/threads/want-to-add-a-folder-in-jffs-but-its-in-read-only-need-jffs-expert.56035/


Jack

**Comment by JackMerlin** [comment]
I have not heard back from you and want to make sure your issue is resolved. If you are still experiencing the issue, please tell me, so I can try to help.

I closed this issue, if your problem is not solved, please reopen this issue.
